spring.profiles.active: dev

spring:
    cache:
        guava:
            spec:expireAfterWrite=30s
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        # Keep the connection alive if idle for a long time (needed in production)
        testWhileIdle: true
        validationQuery: SELECT 1
    # Mybatis configuration
mybatis:
    typeAliasesPackage: net.ebook.model
    mapperLocations: classpath:mapper/*.xml
---
#开发环境
spring:
    profiles: dev
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/ebook?useUnicode=yes&characterEncoding=utf-8
        username: root
        password: cxz6518

server:
    port: 8080

logging.config: classpath:log4j2.yaml

---
#生产环境
spring:
    profiles: online
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/ebook?useUnicode=yes&characterEncoding=utf-8
        username: root
        password: cxz00429

server:
    port: 8080

logging.config: classpath:log4j2.online.yaml
logging.access.directory: /home/share/log

